---
- name: Basic setup
  tags: basic
  block:
    - name: Upgrade all existing packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      tags:
        - basic_upgradepackages
    - name: Install basic packages
      ansible.builtin.apt:
        name:
          - acl # For easy provisioning when using a non-vagrant user
          - fzf
          - ripgrep
          - bat
          - firefox
          - rlwrap
          - cmake
          - xinit
          - x11-utils
          - x11-xserver-utils
        update_cache: true
      tags:
        - basic_packages
    - name: Set Swedish as the default keyboard layout
      ansible.builtin.include_role:
        name: "gantsign.keyboard"
      vars:
        - keyboard_model: pc105
        - keyboard_layout: se
      tags:
        - basic_kblayout
    - name: Set timezone to Europe/Stockholm
      timezone:
        name: Europe/Stockholm
      tags:
        - basic_timezone

- name: Create own user
  tags: basic
  block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
      tags:
        - basic_user
    - name: Create user sudoers file
      ansible.builtin.file:
        path: "/etc/sudoers.d/{{ username }}"
        state: touch
      tags:
        - basic_sudoersfile
    - name: Don't require password for user when running sudo commands
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ username }}"
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
        state: present
      tags:
        - basic_nopasswd
  when:
    username != "vagrant"
