---
- name: Set up shell
  tags: shell
  block:
    - name: Install zsh
      ansible.builtin.apt:
        name:
          - zsh
        update_cache: true
      tags:
        - shell_packages
    - name: Set zsh as default shell
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/zsh
      tags:
        - shell_default
    - name: Install oh-my-zsh
      ansible.builtin.include_role:
        name: "gantsign.oh-my-zsh"
      vars:
        users:
          - username: "{{ username }}"
            oh_my_zsh:
              theme: powerlevel10k/powerlevel10k
              plugins:
                - git
      tags:
        - shell_ohmyzsh
    - name: Create the ~/.fonts directory
      become_user: "{{ username }}"
      ansible.builtin.file:
        path: "/home/{{ username }}/.fonts/"
        state: directory
        mode: '0755'
      tags:
        - shell_createfontsdir
    - name: Download MesloLGS fonts
      become_user: "{{ username }}"
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "/home/{{ username }}/.fonts/"
      loop:
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
      tags:
        - shell_downloadfonts
    - name: Install Powerlevel10k zsh theme
      become_user: "{{ username }}"
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"
        clone: true
        depth: 1
        version: master
      tags:
        - shell_p10k
    - name: Copy configuration files
      become_user: "{{ username }}"
      ansible.builtin.get_url:
        url: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {src: "{{ configfilerepo }}/zsh/.zshrc",
           dest: "/home/{{ username }}/"}
        - {src: "{{ configfilerepo }}/p10k/.p10k.zsh",
           dest: "/home/{{ username }}/"}
      tags:
        - shell_configuration
