---
- hosts: all
  become: true
  vars:
    username: vagrant
    configfilerepo: "https://raw.githubusercontent.com/Daedrus/configfiles/main"
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - git
          - neovim
          - rxvt-unicode
          - xinit
          - x11-utils
          - x11-xserver-utils
          - sddm
          - i3
          - zsh
          - fzf
        update_cache: true
    - name: Set Swedish as the default keyboard layout
      ansible.builtin.include_role:
        name: "gantsign.keyboard"
      vars:
        - keyboard_model: pc105
        - keyboard_layout: se
    - name: Set zsh as default shell
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/zsh
    - name: Install oh-my-zsh
      ansible.builtin.include_role:
        name: "gantsign.oh-my-zsh"
      vars:
        users:
          - username: "{{ username }}"
            oh_my_zsh:
              theme: powerlevel10k/powerlevel10k
              plugins:
                - git
    - name: Create the ~/.fonts directory
      become_user: "{{ username }}"
      ansible.builtin.file:
        path: "/home/{{ username }}/.fonts/"
        state: directory
        mode: '0755'
    - name: Download MesloLGS fonts
      become_user: "{{ username }}"
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "/home/{{ username }}/.fonts/"
      loop:
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    - name: Install Powerlevel10k zsh theme
      become_user: "{{ username }}"
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k"
        clone: true
        depth: 1
        version: master
    - name: Set nvim as the default editor
      community.general.alternatives:
        name: "{{ item }}"
        path: /usr/bin/nvim
      loop:
        - editor
        - vim
        - vi
    - name: Make sure directory structure is OK for vim-plug
      become_user: "{{ username }}"
      ansible.builtin.file:
        path: "/home/{{ username }}/.local/share/nvim/site/autoload"
        state: directory
        mode: '0755'
    - name: Install vim-plug
      become_user: "{{ username }}"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "/home/{{ username }}/.local/share/nvim/site/autoload/"
    - name: Create necessary configuration folders
      become_user: "{{ username }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/home/{{ username }}/.config/i3/"
        - "/home/{{ username }}/.config/nvim/"
    - name: Copy configuration files
      become_user: "{{ username }}"
      ansible.builtin.get_url:
        url: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {src: "{{ configfilerepo }}/i3/config",
           dest: "/home/{{ username }}/.config/i3/"}
        - {src: "{{ configfilerepo }}/i3/i3status.conf",
           dest: "/home/{{ username }}/.config/i3/"}
        - {src: "{{ configfilerepo }}/zsh/.zshrc",
           dest: "/home/{{ username }}/"}
        - {src: "{{ configfilerepo }}/p10k/.p10k.zsh",
           dest: "/home/{{ username }}/"}
        - {src: "{{ configfilerepo }}/nvim/init.vim",
           dest: "/home/{{ username }}/.config/nvim/"}
        - {src: "{{ configfilerepo }}/nvim/coc-settings.json",
           dest: "/home/{{ username }}/.config/nvim/"}
        - {src: "{{ configfilerepo }}/X/.Xresources",
           dest: "/home/{{ username }}/"}
