---
- name: Set up i3-gaps window manager
  tags: windowmgr
  block:
    - name: Register the Regolith public key
      ansible.builtin.shell:
        cmd: >
          wget -qO - https://regolith-desktop.org/regolith.key |
          gpg --dearmor |
          tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null
      args:
        warn: no
      tags:
        - windowmgr_regolithkey
    - name: Add the Regolith repo URL to apt
      ansible.builtin.shell:
        cmd: >
          echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg]
          https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main" |
          tee /etc/apt/sources.list.d/regolith.list
      args:
        warn: no
      tags:
        - windowmgr_regolithrepo
    - name: Install i3-gaps
      ansible.builtin.apt:
        name:
          - i3-gaps
        update_cache: true
      tags:
        - windowmgr_packages
    # - name: Set i3-gaps as the default window manager
    #   community.general.alternatives:
    #     name: x-window-manager
    #     path: /usr/bin/i3
    #   tags:
    #     - windowmgr_default
    - name: Create configuration folder
      become_user: "{{ username }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/home/{{ username }}/.config/i3/"
      tags:
        - windowmgr_configurationdir
    - name: Copy configuration files
      become_user: "{{ username }}"
      ansible.builtin.get_url:
        url: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {src: "{{ configfilerepo }}/i3-gaps/config",
           dest: "/home/{{ username }}/.config/i3/"}
        - {src: "{{ configfilerepo }}/i3-gaps/i3status.conf",
           dest: "/home/{{ username }}/.config/i3/"}
      tags:
        - windowmgr_configuration
  when:
    windowmgr == "i3-gaps"

- name: Set up i3 window manager
  tags: windowmgr
  block:
    - name: Install i3
      ansible.builtin.apt:
        name:
          - i3
        update_cache: true
      tags:
        - windowmgr_packages
    - name: Set i3 as the default window manager
      community.general.alternatives:
        name: x-window-manager
        path: /usr/bin/i3
      tags:
        - windowmgr_default
    - name: Create configuration folder
      become_user: "{{ username }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/home/{{ username }}/.config/i3/"
      tags:
        - windowmgr_configurationdir
    - name: Copy configuration files
      become_user: "{{ username }}"
      ansible.builtin.get_url:
        url: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {src: "{{ configfilerepo }}/i3/config",
           dest: "/home/{{ username }}/.config/i3/"}
        - {src: "{{ configfilerepo }}/i3/i3status.conf",
           dest: "/home/{{ username }}/.config/i3/"}
      tags:
        - windowmgr_configuration
  when:
    windowmgr == "i3"

- name: Install wallpaper handler and wallpapers
  tags: windowmgr
  block:
    - name: Install feh
      ansible.builtin.apt:
        name:
          - feh
        update_cache: true
      tags:
        - windowmgr_wallpaperhandler
    - name: Create wallpapers folder
      become_user: "{{ username }}"
      ansible.builtin.file:
        path: "/home/{{ username }}/.wallpapers"
        state: directory
        mode: '0755'
      tags:
        - windowmgr_wallpapersdir
    - name: Download wallpapers
      become_user: "{{ username }}"
      ansible.builtin.unarchive:
        src: https://github.com/catppuccin/wallpapers/archive/refs/heads/main.zip
        dest: "/home/{{ username }}/.wallpapers"
        remote_src: yes
      tags:
        - windowmgr_wallpapers
    - name: Patch windowmgr config to run feh
      become_user: "{{ username }}"
      ansible.builtin.lineinfile:
        path: "/home/{{ username }}/.config/i3/config"
        line: exec_always --no-startup-id feh --recursive --bg-scale --no-fehbg --randomize ~/.wallpapers/*
      tags:
        - windowmgr_wallpaperhandler_configpatch

- name: Install clipboard manager
  tags: windowmgr
  block:
    - name: Install autocutsel
      ansible.builtin.apt:
        name:
          - autocutsel
        update_cache: true
      tags:
        - windowmgr_clipboardmgr
    - name: Patch windowmgr config to run clipboard manager
      become_user: "{{ username }}"
      ansible.builtin.lineinfile:
        path: "/home/{{ username }}/.config/i3/config"
        line: "{{ item }}"
      loop:
        - "exec --no-startup-id autocutsel -s PRIMARY -f"
        - "exec --no-startup-id autocutsel -s CLIPBOARD -f"
      tags:
        - windowmgr_clipboardmgr_configpatch
